theme: jekyll-theme-minimal
remote_theme: pmarsceill/just-the-docs
show_downloads: false
baseurl: /jam-in-a-box

nav:
  - title: Logistics
    url: logistics.html
  - title: Templates
    url: templates.html
